"use strict";

const VAULT_KEY = "basin_nexus_encrypted_v1";
const STAGES = ["Research", "Positioning", "Applied", "Engaging", "Interview", "Offer", "Closed"];
const PUBLIC_EVIDENCE = [
  {id:"ev-public-1",title:"Enterprise pipeline growth",category:"Revenue impact",statement:"Drove 160% year-over-year pipeline growth by improving signal quality, routing, and operating cadence.",tags:["GTM","pipeline","enterprise"],public:true},
  {id:"ev-public-2",title:"Operating-cost reduction",category:"Systems",statement:"Designed system logic that replaced manual routing work and produced $424K in documented operating savings.",tags:["automation","RevOps","systems"],public:true},
  {id:"ev-public-3",title:"Signal-to-action architecture",category:"Systems",statement:"Built inspectable workflows that translate noisy market signals into prioritized research, outreach, and measurable next actions.",tags:["AI","architecture","workflow"],public:true},
  {id:"ev-public-4",title:"Cross-functional operating judgment",category:"Leadership",statement:"Turned field observations into reusable playbooks, clarified ownership boundaries, and redirected technical work when integration assumptions were wrong.",tags:["leadership","enablement","judgment"],public:true},
  {id:"ev-public-5",title:"Cybersecurity-informed rigor",category:"Cybersecurity",statement:"Applies security-style verification, least-privilege thinking, and evidence discipline to revenue systems and operational decisions.",tags:["cybersecurity","risk","governance"],public:true}
];
const DEMO_OPPORTUNITIES = [
  {id:"op-1",company:"AI Infrastructure Co.",role:"Head of GTM Strategy",location:"San Francisco Bay Area · Hybrid",url:"",fit:92,signal:5,stage:"Positioning",nextMove:"Research the hiring team",why:"Strong overlap across enterprise GTM, systems architecture, and AI-native operating design.",updated:"Today",scores:{role:95,experience:92,momentum:86,workModel:90},evidenceIds:["ev-public-1","ev-public-3","ev-public-4"]},
  {id:"op-2",company:"Revenue Platform Co.",role:"VP, Revenue Architecture",location:"Remote",url:"",fit:87,signal:4,stage:"Applied",nextMove:"Send a proof-led insight note",why:"Direct fit with pipeline architecture, routing logic, and operator enablement.",updated:"Today",scores:{role:94,experience:91,momentum:78,workModel:95},evidenceIds:["ev-public-1","ev-public-2","ev-public-3"]},
  {id:"op-3",company:"Cybersecurity Scale-up",role:"Director, AI Go-to-Market",location:"United States · Remote",url:"",fit:84,signal:4,stage:"Research",nextMove:"Map the operating model",why:"Combines cybersecurity fluency, AI systems work, and enterprise commercial execution.",updated:"Yesterday",scores:{role:90,experience:88,momentum:82,workModel:84},evidenceIds:["ev-public-3","ev-public-5","ev-public-1"]},
  {id:"op-4",company:"Enterprise Automation Co.",role:"Head of Strategic Partnerships",location:"California · Hybrid",url:"",fit:78,signal:3,stage:"Research",nextMove:"Identify warm introductions",why:"Partnership strategy and systems thinking fit; direct partner-channel evidence should be strengthened.",updated:"2 days ago",scores:{role:80,experience:76,momentum:84,workModel:73},evidenceIds:["ev-public-4","ev-public-3"]}
];
const STORY_TEMPLATES = [
  {id:"story-1",title:"Turning pipeline noise into growth",tag:"Enterprise GTM",situation:"Pipeline performance was constrained by inconsistent signals and fragmented execution.",action:"Reworked the operating model around verified inputs, deterministic routing, and measurable handoffs.",result:"Produced 160% year-over-year pipeline growth and a reusable revenue-architecture narrative."},
  {id:"story-2",title:"Replacing manual work with system logic",tag:"RevOps",situation:"Manual routing created operating drag, inconsistency, and unnecessary cost.",action:"Mapped the decision rules and translated them into inspectable automation and governance.",result:"Documented $424K in operating savings while improving consistency and auditability."},
  {id:"story-3",title:"Correcting the architecture before build",tag:"AI systems",situation:"A proposed integration depended on an API and webhook path the vendor did not provide.",action:"Verified the constraint, redirected the design through the existing CRM boundary, and preserved the builder's momentum.",result:"Prevented wasted implementation time and produced a viable proof-of-concept route."},
  {id:"story-4",title:"Turning field learning into enablement",tag:"Leadership",situation:"New operators needed a consistent call methodology across territories without losing local context.",action:"Codified the call flow, objections, language guardrails, and territory variables into reusable references.",result:"Created onboarding infrastructure that preserved execution quality while the team expanded."}
];

const clone = value => JSON.parse(JSON.stringify(value));
const demoState = () => ({version:1,opportunities:clone(DEMO_OPPORTUNITIES),evidence:clone(PUBLIC_EVIDENCE),stories:clone(STORY_TEMPLATES),selectedId:"op-1",stageFilter:"All"});
let state = demoState();
let vaultPassphrase = null;
let vaultUnlocked = false;
let pendingImportEnvelope = null;
let editingOpportunityId = null;
let autoLockTimer = null;

const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const make = (tag,className,text) => {const el=document.createElement(tag);if(className)el.className=className;if(text!==undefined)el.textContent=text;return el};
const icon = name => {const svg=document.createElementNS("http://www.w3.org/2000/svg","svg");const use=document.createElementNS("http://www.w3.org/2000/svg","use");use.setAttribute("href",`#i-${name}`);svg.append(use);return svg};
const uid = prefix => `${prefix}-${Date.now()}-${crypto.getRandomValues(new Uint32Array(1))[0].toString(16)}`;

function showToast(message){const toast=$("#toast");toast.textContent=message;toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("show"),2800)}
function selectedOpportunity(){return state.opportunities.find(item=>item.id===state.selectedId)||state.opportunities[0]||null}
function fitBand(score){return score>=88?"Exceptional":score>=78?"Strong":score>=68?"Promising":"Stretch"}
function safeUrl(value){try{const url=new URL(value);return url.protocol==="https:"?url.href:""}catch{return ""}}
function saveSoon(){if(!vaultUnlocked||!vaultPassphrase)return;clearTimeout(saveSoon.timer);saveSoon.timer=setTimeout(()=>persistVault().catch(()=>showToast("Vault save failed")),250)}
function armAutoLock(){if(!vaultUnlocked)return;clearTimeout(autoLockTimer);autoLockTimer=setTimeout(()=>{if(vaultUnlocked){lockVault();showToast("Vault auto-locked after 15 minutes of inactivity")}},15*60*1000)}

function switchView(name){$$('[data-view-panel]').forEach(panel=>panel.classList.toggle("active",panel.dataset.viewPanel===name));$$('.nav-item').forEach(item=>item.classList.toggle("active",item.dataset.view===name));$(".rail").classList.remove("open");$("#mobile-menu").setAttribute("aria-expanded","false");if(name==="discover")renderSources();if(name==="opportunities")renderOpportunities();if(name==="evidence")renderEvidence();if(name==="outreach")renderOutreachOptions();if(name==="interviews")renderInterviews();if(name==="settings")renderSettings();window.scrollTo({top:0,behavior:"smooth"})}

function render(){renderToday();renderOpportunities();renderEvidence();renderInterviews();renderOutreachOptions();renderSettings();updateSecurityState()}
function renderToday(){
  $("#today-date").textContent=new Intl.DateTimeFormat("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric"}).format(new Date());
  const active=state.opportunities.filter(op=>op.stage!=="Closed");const priority=active.filter(op=>op.fit>=80);const interview=active.filter(op=>op.stage==="Interview");const next=priority.filter(op=>["Research","Positioning","Applied"].includes(op.stage)).length;
  $("#daily-mission").textContent=priority.length?`Advance ${Math.min(3,priority.length)} high-fit opportunities. Complete ${Math.max(1,next)} proof-led moves. Rehearse one interview story.`:"Capture one promising role, score the fit locally, and define one concrete next move.";
  const metrics=[['High-fit roles',priority.length,'Fit ≥ 80'],['Portfolio fit',active.length?`${Math.round(active.reduce((n,o)=>n+o.fit,0)/active.length)}%`:'—','Across active roles'],['Open roles',active.length,'Not closed'],['Interview stage',interview.length,'Current stage']];
  const container=$("#metrics");container.replaceChildren(...metrics.map(([label,value,note])=>{const el=make("div","metric");el.append(make("small","",label),make("strong","",String(value)),make("span","",note));return el}));
  const rows=$("#priority-rows");rows.replaceChildren(...active.sort((a,b)=>b.fit-a.fit).slice(0,7).map(op=>opportunityRow(op,true)));
  const counts={};state.evidence.forEach(ev=>counts[ev.category]=(counts[ev.category]||0)+1);const summary=$("#evidence-summary");summary.replaceChildren(...Object.entries(counts).map(([label,count])=>{const row=make("div","evidence-summary-row");row.append(make("span","",label),make("b","",String(count)));return row}));
  const storyList=$("#story-list");storyList.replaceChildren(...state.stories.slice(0,3).map(story=>{const row=make("div","story-row");row.append(make("strong","",story.title),make("p","",`${story.tag} · ${story.result}`));return row}));renderInspector();
}

function opportunityRow(op,signal){const tr=make("tr",op.id===state.selectedId?"selected":"");tr.dataset.id=op.id;const company=make("td","company-cell");company.append(make("span","company-mark",op.company.split(/\s+/).slice(0,2).map(w=>w[0]).join("").toUpperCase()),make("span","",op.company));const role=make("td","role-cell",op.role);const fit=make("td","fit-cell");fit.append(make("strong","",`${op.fit}%`));const bar=make("span","fit-bar");const level=make("i");level.style.width=`${op.fit}%`;bar.append(level);fit.append(bar);const cells=[company,role,fit];if(signal){const signalCell=make("td");const dots=make("span","signal-dots");for(let i=0;i<5;i++)dots.append(make("i",i<op.signal?"on":""));signalCell.append(dots);cells.push(signalCell)}cells.push(make("td","stage",op.stage),make("td","next-move",op.nextMove));if(!signal)cells.push(make("td","",op.updated||"Today"));const arrow=make("td","row-chevron");arrow.append(icon("chevron"));cells.push(arrow);tr.append(...cells);tr.addEventListener("click",()=>{state.selectedId=op.id;render();if(innerWidth<901)switchView("today")});return tr}

function renderInspector(){const panel=$("#inspector");const op=selectedOpportunity();panel.replaceChildren();if(!op){panel.append(make("div","inspector-empty","Select an opportunity to inspect fit, evidence, and next move."));return}const head=make("div","inspector-head");const company=make("div","inspector-company");company.append(make("span","company-mark",op.company.split(/\s+/).slice(0,2).map(w=>w[0]).join("").toUpperCase()));const copy=make("div");copy.append(make("h2","",op.company),make("p","",`${op.role} · ${op.location||"Location open"}`));company.append(copy);head.append(company);if(safeUrl(op.url)){const link=make("a","text-button","View role");link.href=safeUrl(op.url);link.target="_blank";link.rel="noopener noreferrer";head.append(link)}panel.append(head);
  panel.append(inspectorSection("Why this fits",op.why||"Add a concise fit hypothesis to focus your research."));const matched=make("section","inspector-section");matched.append(make("h3","","Matched evidence"));const evidence=(op.evidenceIds||[]).map(id=>state.evidence.find(ev=>ev.id===id)).filter(Boolean);(evidence.length?evidence:state.evidence.slice(0,2)).forEach((ev,index)=>{const card=make("div",`evidence-match${index===0?" active":""}`);card.append(make("strong","",ev.title),make("p","",ev.statement));matched.append(card)});panel.append(matched);
  const breakdown=make("section","inspector-section");const title=make("h3","",`Fit score breakdown · ${op.fit}%`);breakdown.append(title);const lines=make("div","score-breakdown");Object.entries(op.scores||{role:op.fit,experience:op.fit,momentum:op.fit,workModel:op.fit}).forEach(([key,value])=>{const labels={role:"Role alignment",experience:"Experience match",momentum:"Company momentum",workModel:"Location / flexibility"};const line=make("div","score-line");line.append(make("span","",labels[key]||key));const track=make("i");const fill=make("b");fill.style.width=`${value}%`;track.append(fill);line.append(track,make("span","",`${value}%`));lines.append(line)});breakdown.append(lines);panel.append(breakdown);
  const move=make("section","inspector-section");move.append(make("h3","","Next move"));const card=make("div","next-card");card.append(make("strong","",op.nextMove),make("p","",`Stage: ${op.stage} · Keep the action specific, observable, and small enough to complete today.`));move.append(card);panel.append(move);const actions=make("div","inspector-actions");const advance=make("button","primary-button","Advance stage");advance.addEventListener("click",()=>advanceStage(op));const edit=make("button","outline-button","Edit opportunity");edit.addEventListener("click",()=>openOpportunityModal(op));actions.append(advance,edit);panel.append(actions)}
function inspectorSection(title,text){const section=make("section","inspector-section");section.append(make("h3","",title),make("p","",text));return section}
function advanceStage(op){const index=STAGES.indexOf(op.stage);if(index<STAGES.length-1)op.stage=STAGES[index+1];op.updated="Today";saveSoon();render();showToast(`Advanced to ${op.stage}`)}

function renderOpportunities(){const filters=$("#stage-filters");filters.replaceChildren(...["All",...STAGES].map(stage=>{const button=make("button",`filter-chip${state.stageFilter===stage?" active":""}`,stage);button.addEventListener("click",()=>{state.stageFilter=stage;renderOpportunities()});return button}));const list=state.stageFilter==="All"?state.opportunities:state.opportunities.filter(op=>op.stage===state.stageFilter);const rows=$("#all-opportunity-rows");if(!list.length){const tr=make("tr");const td=make("td","empty-row","No opportunities in this stage.");td.colSpan=7;tr.append(td);rows.replaceChildren(tr);return}rows.replaceChildren(...list.sort((a,b)=>b.fit-a.fit).map(op=>opportunityRow(op,false)))}
function renderEvidence(){const grid=$("#evidence-grid");grid.replaceChildren(...state.evidence.map(ev=>{const card=make("article","evidence-card");card.append(make("small","",`${ev.category}${ev.public?" · public-safe":" · private"}`),make("h2","",ev.title),make("p","",ev.statement));const tags=make("div","tag-row");(ev.tags||[]).forEach(tag=>tags.append(make("span","",`#${tag}`)));card.append(tags);return card}))}
function renderInterviews(){const board=$("#interview-board");board.replaceChildren(...state.stories.map(story=>{const card=make("article","interview-card");card.append(make("small","",story.tag),make("h2","",story.title));[["Situation",story.situation],["Action",story.action],["Result",story.result]].forEach(([label,text])=>{const part=make("div","story-part");part.append(make("b","",label),make("p","",text));card.append(part)});return card}))}
function renderOutreachOptions(){const select=$("#outreach-opportunity");if(!select)return;select.replaceChildren(...state.opportunities.map(op=>{const option=make("option","",`${op.company} — ${op.role}`);option.value=op.id;return option}))}

function renderSources(){const role=$("#discover-role").value;const location=$("#discover-location").value;const keywords=$("#discover-keywords").value.trim();const query=[`"${role}"`,location,keywords,"jobs"].filter(Boolean).join(" ");const sources=[{name:"Google Jobs",url:`https://www.google.com/search?q=${encodeURIComponent(query)}`},{name:"LinkedIn",url:`https://www.linkedin.com/jobs/search/?keywords=${encodeURIComponent([role,keywords].filter(Boolean).join(" "))}&location=${encodeURIComponent(location)}`},{name:"Wellfound",url:`https://wellfound.com/jobs?query=${encodeURIComponent([role,keywords].filter(Boolean).join(" "))}`},{name:"YC Work",url:`https://www.ycombinator.com/jobs?query=${encodeURIComponent([role,keywords].filter(Boolean).join(" "))}`}];const grid=$("#source-grid");grid.replaceChildren(...sources.map(source=>{const link=make("a","source-link");link.href=source.url;link.target="_blank";link.rel="noopener noreferrer";link.append(make("span","",source.name),icon("external"));return link}))}

function scoreDescription(){const text=$("#jd-input").value.toLowerCase().trim();const result=$("#score-result");if(text.length<80){result.replaceChildren(make("span","","—"),make("strong","","More context needed"),make("p","","Paste at least a short role description so the local score has useful signal."));return}const groups=[{weight:38,words:["gtm","go-to-market","revenue","business development","pipeline","enterprise"]},{weight:26,words:["systems","architecture","operations","revops","automation","process"]},{weight:21,words:["ai","artificial intelligence","data","technical","product-led","platform"]},{weight:15,words:["remote","hybrid","california","san francisco","bay area"]}];let score=25;const hits=[];groups.forEach(group=>{const found=group.words.filter(word=>text.includes(word));score+=Math.min(group.weight,found.length*(group.weight/3));hits.push(...found)});score=Math.min(98,Math.round(score));result.replaceChildren(make("span","",`${score}%`),make("strong","",`${fitBand(score)} fit`),make("p","",hits.length?`Signals found: ${[...new Set(hits)].slice(0,7).join(", ")}.`:'The description has limited overlap with the current target lanes.'));showToast("Scored locally — nothing was transmitted")}

function generateOutreach(){const op=state.opportunities.find(item=>item.id===$("#outreach-opportunity").value);if(!op)return;const evidence=(op.evidenceIds||[]).map(id=>state.evidence.find(ev=>ev.id===id)).filter(Boolean)[0]||state.evidence[0];const audience=$("#outreach-audience").value;const opening=audience==="Warm introduction"?`I’m exploring the ${op.role} opportunity at ${op.company} and would value a thoughtful introduction if you believe the fit is real.`:`I’m reaching out about the ${op.role} opportunity at ${op.company}. The role’s emphasis on ${op.why.toLowerCase()} maps closely to the systems work I’ve been doing.`;$("#outreach-output").value=`${opening}\n\nOne relevant proof point: ${evidence.statement}\n\nI’d welcome a short conversation to compare the operating problems behind the role with the systems I’ve built.\n\nLeon`;showToast("Draft generated locally")}

function openOpportunityModal(op=null){editingOpportunityId=op?.id||null;const form=$("#opportunity-form");form.reset();const stage=form.elements.stage;stage.replaceChildren(...STAGES.map(value=>{const option=make("option","",value);option.value=value;return option}));if(op){$("#opportunity-modal-title").textContent="Edit opportunity";["company","role","location","url","stage","fit","nextMove","why"].forEach(name=>form.elements[name].value=op[name]??"")}else{$("#opportunity-modal-title").textContent="Add opportunity";form.elements.stage.value="Research";form.elements.fit.value="70"}$("#opportunity-modal").showModal()}
function saveOpportunity(event){event.preventDefault();const form=$("#opportunity-form");if(!form.reportValidity())return;const data=new FormData(form);const url=data.get("url")?.trim();if(url&&!safeUrl(url)){showToast("Only secure https:// source URLs are accepted");return}const existing=state.opportunities.find(op=>op.id===editingOpportunityId);const value={id:existing?.id||uid("op"),company:String(data.get("company")).trim(),role:String(data.get("role")).trim(),location:String(data.get("location")).trim(),url:safeUrl(url||""),stage:String(data.get("stage")),fit:Math.max(0,Math.min(100,Number(data.get("fit"))||0)),signal:existing?.signal||3,nextMove:String(data.get("nextMove")).trim(),why:String(data.get("why")).trim(),updated:"Today",scores:existing?.scores||{role:75,experience:75,momentum:70,workModel:75},evidenceIds:existing?.evidenceIds||state.evidence.slice(0,3).map(ev=>ev.id)};if(existing)Object.assign(existing,value);else state.opportunities.unshift(value);state.selectedId=value.id;$("#opportunity-modal").close();saveSoon();render();showToast(existing?"Opportunity updated":"Opportunity added")}
function saveEvidence(event){event.preventDefault();const form=$("#evidence-form");if(!form.reportValidity())return;const text=`${form.elements.title.value} ${form.elements.statement.value} ${form.elements.tags.value}`;if(containsSensitivePattern(text)){showToast("Potential email, phone number, credential, or private URL detected — remove it first");return}const ev={id:uid("ev"),title:form.elements.title.value.trim(),category:form.elements.category.value,statement:form.elements.statement.value.trim(),tags:form.elements.tags.value.split(",").map(tag=>tag.trim()).filter(Boolean).slice(0,12),public:false};state.evidence.unshift(ev);$("#evidence-modal").close();saveSoon();render();showToast("Evidence added to this workspace")}
function containsSensitivePattern(text){return /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/i.test(text)||/\b(?:\+?1[-.\s]?)?\(?\d{3}\)?[-.\s]\d{3}[-.\s]\d{4}\b/.test(text)||/https?:\/\/(?:docs\.google|drive\.google|hubspot|slack|notion)\./i.test(text)||/\b(?:api[_-]?key|password|secret|token|credential)s?\b\s*[:=]/i.test(text)}

async function deriveKey(passphrase,salt){const material=await crypto.subtle.importKey("raw",new TextEncoder().encode(passphrase),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt,iterations:250000,hash:"SHA-256"},material,{name:"AES-GCM",length:256},false,["encrypt","decrypt"])}
const bytesToBase64=bytes=>btoa(String.fromCharCode(...bytes));
const base64ToBytes=value=>Uint8Array.from(atob(value),char=>char.charCodeAt(0));
async function encryptState(data,passphrase){const salt=crypto.getRandomValues(new Uint8Array(16));const iv=crypto.getRandomValues(new Uint8Array(12));const key=await deriveKey(passphrase,salt);const ciphertext=await crypto.subtle.encrypt({name:"AES-GCM",iv},key,new TextEncoder().encode(JSON.stringify(data)));return{format:"basin-nexus-v1",kdf:"PBKDF2-SHA256",iterations:250000,cipher:"AES-256-GCM",salt:bytesToBase64(salt),iv:bytesToBase64(iv),ciphertext:bytesToBase64(new Uint8Array(ciphertext))}}
function validateEnvelope(envelope){if(!envelope||typeof envelope!=="object"||envelope.format!=="basin-nexus-v1"||envelope.kdf!=="PBKDF2-SHA256"||envelope.iterations!==250000||envelope.cipher!=="AES-256-GCM")throw new Error("Unsupported vault format");const salt=base64ToBytes(envelope.salt);const iv=base64ToBytes(envelope.iv);const data=base64ToBytes(envelope.ciphertext);if(salt.length!==16||iv.length!==12||data.length<16||data.length>5_000_000)throw new Error("Invalid vault envelope");return{salt,iv,data}}
async function decryptState(envelope,passphrase){const {salt,iv,data}=validateEnvelope(envelope);const key=await deriveKey(passphrase,salt);const plaintext=await crypto.subtle.decrypt({name:"AES-GCM",iv},key,data);const parsed=JSON.parse(new TextDecoder().decode(plaintext));validateImportedState(parsed);return parsed}
function validateImportedState(value){if(!value||typeof value!=="object"||!Array.isArray(value.opportunities)||!Array.isArray(value.evidence)||!Array.isArray(value.stories))throw new Error("Invalid vault data");if(value.opportunities.length>500||value.evidence.length>1000||value.stories.length>500)throw new Error("Vault exceeds safe limits")}
async function persistVault(){const envelope=await encryptState(state,vaultPassphrase);localStorage.setItem(VAULT_KEY,JSON.stringify(envelope));updateSecurityState();armAutoLock()}

function openVaultModal(mode){const form=$("#vault-form");form.reset();form.dataset.mode=mode;$("#vault-error").textContent="";const creating=mode==="create";$("#vault-modal-title").textContent=creating?"Create private vault":"Unlock private vault";$("#confirm-passphrase-wrap").hidden=!creating;form.elements.confirm.required=creating;$("#save-vault").textContent=creating?"Encrypt locally":"Unlock locally";$("#vault-modal").showModal()}
async function handleVault(event){event.preventDefault();const form=$("#vault-form");if(!form.reportValidity())return;const pass=form.elements.passphrase.value;const mode=form.dataset.mode;const error=$("#vault-error");error.textContent="";try{if(mode==="create"){if(pass!==form.elements.confirm.value)throw new Error("Passphrases do not match");pendingImportEnvelope=null;vaultPassphrase=pass;vaultUnlocked=true;await persistVault();showToast("Private vault created and encrypted on this device")}else{const envelope=pendingImportEnvelope||JSON.parse(localStorage.getItem(VAULT_KEY));const nextState=await decryptState(envelope,pass);if(pendingImportEnvelope){localStorage.setItem(VAULT_KEY,JSON.stringify(pendingImportEnvelope));pendingImportEnvelope=null}state=nextState;vaultPassphrase=pass;vaultUnlocked=true;armAutoLock();showToast("Private vault unlocked locally")}form.reset();$("#vault-modal").close();render()}catch(err){error.textContent=mode==="unlock"?"Unable to unlock. Check the passphrase and file integrity.":err.message}}
function lockVault(){clearTimeout(autoLockTimer);autoLockTimer=null;pendingImportEnvelope=null;vaultPassphrase=null;vaultUnlocked=false;$("#vault-form").reset();state=demoState();render();showToast("Vault locked; sensitive state cleared from memory")}
function deleteVault(){if(!confirm("Delete the encrypted Basin::Nexus vault from this browser? This cannot be undone without an exported backup."))return;localStorage.removeItem(VAULT_KEY);pendingImportEnvelope=null;vaultPassphrase=null;vaultUnlocked=false;state=demoState();render();showToast("Local vault deleted")}
function exportVault(){const stored=localStorage.getItem(VAULT_KEY);if(!stored)return;const blob=new Blob([stored],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`basin-nexus-backup-${new Date().toISOString().slice(0,10)}.nexus`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast("Encrypted backup exported")}
async function importVault(file){if(!file||file.size>5_000_000){showToast("Choose an encrypted Basin::Nexus file under 5 MB");return}try{const text=await file.text();const envelope=JSON.parse(text);validateEnvelope(envelope);pendingImportEnvelope=envelope;vaultUnlocked=false;vaultPassphrase=null;state=demoState();openVaultModal("unlock");showToast("Encrypted backup loaded; unlock to verify")}catch{pendingImportEnvelope=null;showToast("Invalid encrypted backup")}}
function updateSecurityState(){const exists=Boolean(localStorage.getItem(VAULT_KEY));const stateEl=$("#security-state span");const vaultButton=$("#vault-button");if(vaultUnlocked){stateEl.textContent="Encrypted vault unlocked";vaultButton.querySelector("span").textContent="Lock vault"}else if(exists){stateEl.textContent="Encrypted vault locked";vaultButton.querySelector("span").textContent="Unlock vault"}else{stateEl.textContent="Ephemeral demo";vaultButton.querySelector("span").textContent="Create private vault"}}
function renderSettings(){const exists=Boolean(localStorage.getItem(VAULT_KEY));$("#vault-description").textContent=vaultUnlocked?"Encrypted with AES-256-GCM. The passphrase remains only in memory for this tab.":exists?"An encrypted vault exists on this device and is currently locked.":"No real data is persisted. Current changes disappear when this tab closes or reloads.";$("#settings-vault").textContent=vaultUnlocked?"Lock vault":exists?"Unlock vault":"Create vault";$("#export-vault").disabled=!exists;$("#delete-vault").disabled=!exists}

function globalFilter(){const query=$("#global-search").value.trim().toLowerCase();if(!query){render();return}const matches=state.opportunities.filter(op=>`${op.company} ${op.role} ${op.nextMove} ${op.why}`.toLowerCase().includes(query));const rows=$("#priority-rows");rows.replaceChildren(...matches.map(op=>opportunityRow(op,true)));if(!matches.length){const tr=make("tr");const td=make("td","empty-row","No matching opportunities.");td.colSpan=7;tr.append(td);rows.replaceChildren(tr)}}

function bind(){
  $$('button[value="cancel"]').forEach(button=>button.addEventListener("click",event=>{event.preventDefault();button.closest("dialog")?.close()}));
  $("#primary-nav").addEventListener("click",event=>{const item=event.target.closest(".nav-item");if(item)switchView(item.dataset.view)});$$('[data-view-link]').forEach(button=>button.addEventListener("click",()=>switchView(button.dataset.viewLink)));$$('[data-open-modal="opportunity"]').forEach(button=>button.addEventListener("click",()=>openOpportunityModal()));$$('[data-open-modal="evidence"]').forEach(button=>button.addEventListener("click",()=>$("#evidence-modal").showModal()));
  $("#mobile-menu").addEventListener("click",()=>{const rail=$(".rail");rail.classList.toggle("open");$("#mobile-menu").setAttribute("aria-expanded",String(rail.classList.contains("open")))});$("#global-search").addEventListener("input",globalFilter);$("#discover-role").addEventListener("change",renderSources);$("#discover-location").addEventListener("change",renderSources);$("#discover-keywords").addEventListener("input",renderSources);$("#score-job").addEventListener("click",scoreDescription);$("#generate-outreach").addEventListener("click",generateOutreach);$("#copy-outreach").addEventListener("click",async()=>{const text=$("#outreach-output").value;if(!text)return;await navigator.clipboard.writeText(text);showToast("Draft copied")});
  $("#opportunity-form").addEventListener("submit",saveOpportunity);$("#evidence-form").addEventListener("submit",saveEvidence);$("#vault-form").addEventListener("submit",handleVault);$("#vault-button").addEventListener("click",()=>vaultUnlocked?lockVault():openVaultModal(localStorage.getItem(VAULT_KEY)?"unlock":"create"));$("#settings-vault").addEventListener("click",()=>vaultUnlocked?lockVault():openVaultModal(localStorage.getItem(VAULT_KEY)?"unlock":"create"));$("#privacy-button").addEventListener("click",()=>switchView("settings"));$("#export-vault").addEventListener("click",exportVault);$("#delete-vault").addEventListener("click",deleteVault);$("#import-vault").addEventListener("change",event=>importVault(event.target.files[0]));
  $$('dialog').forEach(dialog=>dialog.addEventListener("click",event=>{if(event.target===dialog)dialog.close()}));
  ["pointerdown","keydown"].forEach(type=>document.addEventListener(type,()=>{if(vaultUnlocked)armAutoLock()},{passive:true}));
  window.addEventListener("pagehide",()=>{vaultPassphrase=null;clearTimeout(autoLockTimer)});
}

bind();
render();
renderSources();
if(localStorage.getItem(VAULT_KEY))showToast("Encrypted vault detected — unlock when ready");
