# Gitpod Configuration for BASIN::NEXUS
# One-click demo environment for recruiters and hiring managers

image: gitpod/workspace-full

tasks:
  - name: Setup & Run
    init: |
      npm install
    command: |
      echo "🚀 BASIN::NEXUS is starting..."
      echo "📋 Add your VITE_GEMINI_API_KEY to .env (or use demo mode)"
      cp .env.example .env 2>/dev/null || true
      npm run dev

ports:
  - port: 5173
    onOpen: open-preview
    visibility: public
    name: BASIN::NEXUS

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - bradlc.vscode-tailwindcss

github:
  prebuilds:
    master: true
    pullRequests: true
